Added View Models
ectky/ProjectManagementApp pull request #14
Opened 2024-06-05 18:49 UTC by ivomihailov06

2024-06-05 18:55 UTC, ectky commented on ProjectManagementMVC/ViewModels/ReportProjectEditVM.cs
> -        public IEnumerable<SelectListItem> Reports { get; set; }
Защо си изтрил това?

2024-06-05 20:08 UTC, ivomihailov06 commented on ProjectManagementMVC/ViewModels/ReportProjectEditVM.cs
> -        public IEnumerable<SelectListItem> Reports { get; set; }
Сега ще го върна

2024-06-05 20:12 UTC, ectky requested changes

2024-06-05 20:12 UTC, ectky commented on ProjectManagementMVC/ViewModels/ReportProjectEditVM.cs
> -        public IEnumerable<SelectListItem> Projects { get; set; }
И това също

2024-06-06 04:56 UTC, ectky approved these changes

2024-06-06 05:04 UTC, merged