Petkov06 logic and views
ectky/ProjectManagementApp pull request #15
Opened 2024-06-13 05:45 UTC by Petkov06

2024-06-13 11:41 UTC, ectky requested changes

2024-06-13 11:41 UTC, ectky commented on ProjectManagement.Data/Migrations/20240610200604_ReportProject.cs
> +                name: "ProjectId1",
имаш грешка в миграцията, нещо не е наред в дб контекста

2024-06-13 11:41 UTC, ectky commented on ProjectManagement.Data/ProjectManagementDbContext.cs
> +            modelBuilder.Entity<ReportProject>()
пробвай да добавиш още едно такова но за ReportProject -> ProjectId

2024-06-13 11:41 UTC, ectky commented on ProjectManagement.Data/Repos/ProjectRepository.cs
> +        ////UpdateAsync ??
Изтрий ненужния код

2024-06-13 11:41 UTC, ectky commented on ProjectManagement.Data/Repos/TaskRepository.cs
> +            return MapToEnumerableOfModel(await _dbSet.Where(s => s.Status == null).ToListAsync());
защо е това?

2024-06-13 11:41 UTC, ectky commented on ProjectManagement.Shared/Dtos/ReportProjectDto.cs
> +        public virtual List<ReportProjectDto> ReportProjects { get; set; }
това няма смисъл

2024-06-13 11:41 UTC, ectky commented on ProjectManagementMVC/Controllers/ProjectController.cs
> +            string? loggedUsername = User.FindFirst(ClaimTypes.Name)?.Value;
този username  за какво е?

2024-06-13 11:41 UTC, ectky commented on ProjectManagementMVC/Program.cs
> +using (var scope = app.Services.CreateScope())
това нямаше ли го преди?

2024-06-13 11:41 UTC, ectky commented on ProjectManagementMVC/Views/Project/Details.cshtml
> +            @Html.DisplayFor(model => model.Tasks)
това не мисля че излиза адекватно

2024-06-13 11:41 UTC, ectky commented on ProjectManagementMVC/Views/Report/Details.cshtml
> +        @*
защо е закоментирано?

2024-06-13 11:41 UTC, ectky commented on ProjectManagementMVC/Views/Shared/_Layout.cshtml
>                              <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
направи го да излиза логин е рег само ако не е логнат user-a

2024-06-13 11:41 UTC, ectky commented on ProjectManagementMVC/Views/Shared/_Layout.cshtml
> +                        @if (Context.User?.FindFirst(ClaimTypes.Role)?.Value == UserRole.Employee.ToString() ||
има ли логика employee да може да вижда всички user-и, прегледай и другите бутони и authorize attribute-ите

2024-06-13 11:41 UTC, ectky commented on ProjectManagementMVC/Views/User/List.cshtml
> +            @Html.DisplayNameFor(model => model.ProjectId)
какво ще гледаме на тези идта в листа?

2024-06-13 11:41 UTC, ectky commented on ProjectManagementMVC/Views/User/List.cshtml
> +            @Html.DisplayNameFor(model => model.RoleId)
какво ще гледаме на тези идта в листа?

2024-06-13 11:41 UTC, ectky commented on ProjectManagementMVC/appsettings.json
> +    "DefaultConnection": "Data Source=pmg3012\\SQLEXPRESS;Initial Catalog=ProjectManagementMVC;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=
.

2024-06-13 15:28 UTC, Petkov06 commented on ProjectManagementMVC/Views/Report/Details.cshtml
> +        @*
защото няма Location.

2024-06-14 18:03 UTC, ectky requested changes

2024-06-14 18:03 UTC, ectky commented on ProjectManagament.Services/ProjectsService.cs
> +                throw new ArgumentException($"Pet with ID {userId} does not exist.");
Pet

2024-06-14 18:03 UTC, ectky commented on ProjectManagament.Services/ProjectsService.cs
> +                throw new ArgumentException($"Vaccine with ID {projectId} does not exist.");
?

2024-06-14 18:03 UTC, ectky commented on ProjectManagament.Services/ReportProjectsService.cs
> +                throw new ArgumentException($"Pet with ID {reportId} does not exist.");
?

2024-06-14 18:03 UTC, ectky commented on ProjectManagament.Services/ReportProjectsService.cs
> +                throw new ArgumentException($"Vaccine with ID {projectId} does not exist.");
?

2024-06-14 18:03 UTC, ectky commented on ProjectManagementMVC/ViewModels/ReportProjectEditVM.cs
> +        //[DisplayName("Reports")]
?

2024-06-14 18:03 UTC, ectky commented on ProjectManagementMVC/Views/Project/GetProject.cshtml
> +    ViewBag.Title = "Get Project";
Какъв е тоя гет проект?

2024-06-14 18:03 UTC, ectky commented on ProjectManagementMVC/Views/Shared/_Layout.cshtml
> -                    @if (Context.User.Identity.IsAuthenticated)
и защо ги махна от тука и ги сложи горе?

2024-06-14 22:38 UTC, Petkov06 commented on ProjectManagementMVC/Views/Shared/_Layout.cshtml
> -                    @if (Context.User.Identity.IsAuthenticated)
къде горе?

2024-06-15 06:54 UTC, ectky approved these changes

2024-06-15 07:08 UTC, merged